---
funktional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять желаемое количество одного товара в корзину
  - Пользователь должен иметь возможность удалять товары из корзины
  - После перезагрузки страницы товары в корзине остаются
non-funktional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
implicit:
  - Сайт должен автоматически определять язык интерфейса клиента и менять в соответствии с этим язык сайта 
  - Сайт должен иметь сортировку по цене товаров
  - После оформления заказа корзина должна очищаться автоматически
